version: 2

updates:
  ## ci
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  ## welcome page
  - package-ecosystem: npm
    directory: /welcome-page
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /welcome-page/docker
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  ## compose services
  - package-ecosystem: docker-compose
    directory: /forgejo
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: docker-compose
    directory: /readeck
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: docker-compose
    directory: /database
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: docker-compose
    directory: /gotenberg
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  ## dockerfile services
  - package-ecosystem: docker
    directory: /github-runner
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
