services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.14.0
    container_name: mealie
    restart: unless-stopped
    ports:
      - "9925:9000"
    volumes:
      - mealie-data:/app/data/
    env_file:
      - .env

volumes:
  mealie-data: