services:
  web:
    image: ${REGISTRY_IMAGE:-welcome-page}:${TAG:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '8080:80'
      - '8081:81'
    restart: unless-stopped
