services:
  readeck:
    image: codeberg.org/readeck/readeck:0.22.2
    container_name: readeck
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - data:/readeck

volumes:
  data:
    external: true
    name: readeck_data
