services:
  readeck:
    image: codeberg.org/readeck/readeck:latest
    container_name: readeck
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - readeck-data:/readeck

volumes:
  readeck-data:
