log:
  level: info

runner:
  file: .runner
  capacity: 2
  timeout: 3h
  shutdown_timeout: 30s
  insecure: false
  fetch_interval: 2s
  report_interval: 1s
  labels:
    - "ubuntu-latest:docker://localhost/runner-tools:latest"
    - "self-hosted:host"

cache:
  enabled: true
  dir: /data/cache

container:
  network: bridge
  privileged: false
  docker_host: tcp://dind:2375
  force_pull: false
  valid_volumes:
    - /data/**
